// This file was auto-generated by Fern from our API Definition.

import type * as ArtiqhttpApi from "../index.js";

export interface ExperimentList {
    current_rev: string | null;
    scanning: boolean;
    experiments?: ArtiqhttpApi.ExperimentEntry[] | undefined;
}
