// This file was auto-generated by Fern from our API Definition.

export interface ExperimentEntry {
    name: string;
    file: string;
    class_name: string;
    arginfo: Record<string, unknown>;
    argument_ui: string | null;
    scheduler_defaults: Record<string, unknown>;
}
