// This file was auto-generated by Fern from our API Definition.

export interface ExpId {
    log_level?: number | undefined;
    file: string;
    class_name: string;
    arguments: Record<string, unknown> | null;
    repo_rev: string | null;
}
