// This file was auto-generated by Fern from our API Definition.

import type * as ArtiqhttpApi from "../index.js";

export interface HttpValidationError {
    detail?: ArtiqhttpApi.ValidationError[] | undefined;
}
