// This file was auto-generated by Fern from our API Definition.

import type * as ArtiqhttpApi from "../index.js";

export interface ScheduleItem {
    pipeline: string;
    priority: number;
    due_date: number | null;
    flush: boolean;
    status: string | null;
    repo_msg: string | null;
    expid: ArtiqhttpApi.ExpId;
}
