# Default image, if not specified
image: python:3.11

stages:
  - Static Analysis
  - Test
  - Build
  - Compile Documentation
  - Build Documentation

# Poetry setup shared across jobs
.poetry-setup:
  before_script:
    # Store the CI_JOB_TOKEN so that jobs can access other repositories with the access rights of the triggering user
    - echo -e "machine ${CI_SERVER_HOST}\nlogin gitlab-ci-token\npassword ${CI_JOB_TOKEN}" > ~/.netrc
    # Set up git so that test commits don't fail
    - echo [user] > ~/.gitconfig
    - echo name = Gitlabs CI Testing >> ~/.gitconfig
    - echo email = test@example.com >> ~/.gitconfig
    # Install Poetry
    - pip install poetry poetry-dynamic-versioning
    - poetry --version
    # Configure Poetry to create venv in project directory for easier caching
    - poetry config virtualenvs.in-project true
    # Install dependencies
    - poetry install --with dev

cache:
  key: ${CI_JOB_NAME}
  paths:
    - .venv
    - .cache

### Linting ###

pre-commit:
  extends: .poetry-setup
  stage: Static Analysis
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  script:
    - poetry run pre-commit run --all
  allow_failure: true
  needs: []

### Tests ###

pytest:
  extends: .poetry-setup
  stage: "Test"
  script:
    - poetry run coverage run --omit "tests/*,*/_version.py" -m pytest --junitxml=report.xml
    - poetry run coverage report
  coverage: '/^TOTAL.+?(\d+\%)$/'
  needs: []
  artifacts:
    when: always
    reports:
      junit: report.xml

### Build ###

build-package:
  extends: .poetry-setup
  stage: Build
  needs: []
  script:
    - poetry build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

### Documentation ###

# Build the documentation
make_docs:
  extends: .poetry-setup
  stage: Compile Documentation
  needs: []
  before_script:
    - !reference [.poetry-setup, before_script]
    # Additional system dependencies for docs
    - apt-get update && apt-get install -y librsvg2-bin
  script:
    - poetry run sphinx-apidoc -o docs/autogen "artiq_http"
    - poetry run sphinx-build docs html_out -b html
    - poetry run sphinx-build docs latex -b latex
  artifacts:
    paths:
      - latex
      - html_out
    expire_in: 1 hour

# Build a pdf
pdf_compile:
  needs: ["make_docs"]
  stage: Build Documentation
  image: charlesbaynham/ctanfull
  artifacts:
    paths:
      - "*.pdf"
    name: ${CI_COMMIT_REF_SLUG}_manual.pdf
  script:
    - cd latex
    - make
    - cp *.pdf ..

# Upload the documentation to pages if we're on the master branch
pages:
  image: alpine
  stage: Build Documentation
  needs: ["make_docs"]
  script:
    - cp -r html_out public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
    - if: $CI_COMMIT_TAG
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: manual
