
repos:
  # Several generic fixes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-yaml

  # Sort python imports
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    - id: reorder-python-imports

  # Lint and format the code with ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
