[tool.poetry]
name = "artiq_http"
version = "0.0.0"
description = "A controller for ARTIQ which exposes ARTIQ's functionality as a RESTful API"
authors = ["Charles Baynham <charles.baynham@gmail.com>"]
readme = "README.rst"
packages = [{ include = "artiq_http" }]
include = ["artiq_http/static/**/*", "artiq_http/_version.py", "VERSION.json"]

[tool.poetry.scripts]
aqctl_artiq_http = "artiq_http.main:main"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = { extras = ["standard"], version = "^0.88.0" }
starlette = "^0.22.0"
uvicorn = "*"
pydantic = "*"
sipyco = { git = "https://github.com/m-labs/sipyco.git", rev = "96fcefbea490a9b42c862393860d2e586b05d744" }
pybase64 = "*"
numpy = "*"

[tool.poetry.group.dev.dependencies]
pre-commit = "*"
ruff = "*"
pytest = "*"
coverage = "*"
sphinx = "*"
sphinx-autobuild = "*"
sphinx-rtd-theme = "*"
sphinxcontrib-svg2pdfconverter = "*"
ipython = "*"
notebook = "*"
jupytext = "*"
check-manifest = "*"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "pep440"
format-jinja = """
    {%- if distance == 0 -%}
        {{ serialize_pep440(base) }}
    {%- else -%}
        {{ serialize_pep440(base) }}+{{ commit }}
        {%- if dirty -%}.d{%- endif -%}
    {%- endif -%}
"""

[tool.ruff]
line-length = 120
exclude = ["docs", "artiq_http/_version.py"]

[tool.ruff.lint]
extend-ignore = ["W291"]
