[project]
name = "artiq_http"
version = "0.8.1"
description = "A controller for ARTIQ which exposes ARTIQ's functionality as a RESTful API"
authors = [
    { name = "Charles Baynham", email = "charles.baynham@gmail.com" }
]
readme = "README.rst"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]",
    "starlette",
    "uvicorn",
    "pydantic",
    "sipyco @ git+https://github.com/m-labs/sipyco.git@96fcefbea490a9b42c862393860d2e586b05d744",
    "pybase64",
    "numpy",
    "mcp[cli]>=1.2.0",
    "httpx>=0.24.0",

]

[project.optional-dependencies]
dev = [
    "pre-commit",
    "ruff",
    "pytest",
    "coverage",
    "sphinx",
    "sphinx-autobuild",
    "sphinx-rtd-theme",
    "sphinxcontrib-svg2pdfconverter",
    "ipython",
    "notebook",
    "jupytext",
    "check-manifest",
]

[project.scripts]
aqctl_artiq_http = "artiq_http.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
include = [
    "artiq_http/**/*",
]

[tool.ruff]
line-length = 120
exclude = ["docs"]

[tool.ruff.lint]
extend-ignore = ["W291"]
per-file-ignores = { "test-artiq/repository/*.py" = ["F403", "F405"] }

[tool.pytest.ini_options]
asyncio_mode = "auto"

[dependency-groups]
dev = [
    "pytest (>=9.0.2,<10.0.0)",
    "pytest-asyncio>=1.3.0",
    "ruff (>=0.15.7,<0.16.0)",
]
