# This file was auto-generated by Fern from our API Definition.

import typing

import httpx
from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .core.logging import LogConfig, Logger
from .core.request_options import RequestOptions
from .raw_client import AsyncRawArtiqClient, RawArtiqClient
from .types.experiment_defaults import ExperimentDefaults
from .types.experiment_list import ExperimentList
from .types.schedule_item import ScheduleItem
from .types.submit_and_wait_result import SubmitAndWaitResult

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ArtiqClient:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : str
        The base url to use for requests from the client.

    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from artiq_http_client import ArtiqClient

    client = ArtiqClient(
        base_url="https://yourhost.com/path/to/api",
    )
    """

    def __init__(
        self,
        *,
        base_url: str,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        self._client_wrapper = SyncClientWrapper(
            base_url=base_url,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.Client(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.Client(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
            logging=logging,
        )
        self._raw_client = RawArtiqClient(client_wrapper=self._client_wrapper)

    @property
    def with_raw_response(self) -> RawArtiqClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawArtiqClient
        """
        return self._raw_client

    def root_api_get(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from artiq_http_client import ArtiqClient

        client = ArtiqClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.root_api_get()
        """
        _response = self._raw_client.root_api_get(request_options=request_options)
        return _response.data

    def get_schedule_api_schedule_get(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, ScheduleItem]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, ScheduleItem]
            Successful Response

        Examples
        --------
        from artiq_http_client import ArtiqClient

        client = ArtiqClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.get_schedule_api_schedule_get()
        """
        _response = self._raw_client.get_schedule_api_schedule_get(request_options=request_options)
        return _response.data

    def submit_experiment_api_schedule_post(
        self,
        *,
        file: str,
        class_name: str,
        pipeline: typing.Optional[str] = None,
        priority: typing.Optional[int] = None,
        flush: typing.Optional[bool] = None,
        due_date: typing.Optional[float] = None,
        log_level: typing.Optional[int] = OMIT,
        arguments: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        repo_rev: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Parameters
        ----------
        file : str

        class_name : str

        pipeline : typing.Optional[str]

        priority : typing.Optional[int]

        flush : typing.Optional[bool]

        due_date : typing.Optional[float]

        log_level : typing.Optional[int]

        arguments : typing.Optional[typing.Dict[str, typing.Any]]

        repo_rev : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from artiq_http_client import ArtiqClient

        client = ArtiqClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.submit_experiment_api_schedule_post(
            file="file",
            class_name="class_name",
        )
        """
        _response = self._raw_client.submit_experiment_api_schedule_post(
            file=file,
            class_name=class_name,
            pipeline=pipeline,
            priority=priority,
            flush=flush,
            due_date=due_date,
            log_level=log_level,
            arguments=arguments,
            repo_rev=repo_rev,
            request_options=request_options,
        )
        return _response.data

    def get_devices_api_devices_get(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get the current device_db

        Returns:
            dict: ARTIQ Device_DB

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful Response

        Examples
        --------
        from artiq_http_client import ArtiqClient

        client = ArtiqClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.get_devices_api_devices_get()
        """
        _response = self._raw_client.get_devices_api_devices_get(request_options=request_options)
        return _response.data

    def get_datasets_api_datasets_get(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Get all existing ARTIQ datasets

        This method might return a large output

        Returns:
            dict: All broadcasted ARTIQ datasets

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from artiq_http_client import ArtiqClient

        client = ArtiqClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.get_datasets_api_datasets_get()
        """
        _response = self._raw_client.get_datasets_api_datasets_get(request_options=request_options)
        return _response.data

    def get_dataset_names_api_datasets_names_get(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Get list of all dataset names (keys only)

        Returns a lightweight list of dataset names without their values,
        enabling efficient browsing and searching.

        Returns:
            dict: {"names": ["dataset1", "dataset2", ...]}

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from artiq_http_client import ArtiqClient

        client = ArtiqClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.get_dataset_names_api_datasets_names_get()
        """
        _response = self._raw_client.get_dataset_names_api_datasets_names_get(request_options=request_options)
        return _response.data

    def get_dataset_values_api_datasets_values_get(
        self, *, names: str, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Get values for specific datasets

        Args:
            names: Comma-separated list of dataset names to fetch

        Returns:
            dict: Requested datasets with their values

        Parameters
        ----------
        names : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from artiq_http_client import ArtiqClient

        client = ArtiqClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.get_dataset_values_api_datasets_values_get(
            names="names",
        )
        """
        _response = self._raw_client.get_dataset_values_api_datasets_values_get(
            names=names, request_options=request_options
        )
        return _response.data

    def get_health_api_health_get(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Get backend health and ARTIQ connection status

        Returns:
            dict: Health status including ARTIQ connection state

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from artiq_http_client import ArtiqClient

        client = ArtiqClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.get_health_api_health_get()
        """
        _response = self._raw_client.get_health_api_health_get(request_options=request_options)
        return _response.data

    def cancel_experiment_api_cancel_post(
        self, *, rid: int, force: typing.Optional[bool] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Cancel a running experiment

        Args:
            rid (int): RID of the experiment to cancel
            force (bool): If True, forcibly close the experiment instead of requesting closure

        Parameters
        ----------
        rid : int

        force : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from artiq_http_client import ArtiqClient

        client = ArtiqClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.cancel_experiment_api_cancel_post(
            rid=1,
        )
        """
        _response = self._raw_client.cancel_experiment_api_cancel_post(
            rid=rid, force=force, request_options=request_options
        )
        return _response.data

    def get_explist_api_explist_get(self, *, request_options: typing.Optional[RequestOptions] = None) -> ExperimentList:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExperimentList
            Successful Response

        Examples
        --------
        from artiq_http_client import ArtiqClient

        client = ArtiqClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.get_explist_api_explist_get()
        """
        _response = self._raw_client.get_explist_api_explist_get(request_options=request_options)
        return _response.data

    def get_schedule_item_api_schedule_rid_get(
        self, rid: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ScheduleItem:
        """
        Parameters
        ----------
        rid : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScheduleItem
            Successful Response

        Examples
        --------
        from artiq_http_client import ArtiqClient

        client = ArtiqClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.get_schedule_item_api_schedule_rid_get(
            rid=1,
        )
        """
        _response = self._raw_client.get_schedule_item_api_schedule_rid_get(rid, request_options=request_options)
        return _response.data

    def search_explist_api_explist_search_get(
        self, *, q: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> ExperimentList:
        """
        Parameters
        ----------
        q : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExperimentList
            Successful Response

        Examples
        --------
        from artiq_http_client import ArtiqClient

        client = ArtiqClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.search_explist_api_explist_search_get()
        """
        _response = self._raw_client.search_explist_api_explist_search_get(q=q, request_options=request_options)
        return _response.data

    def get_explist_defaults_api_explist_file_class_name_defaults_get(
        self, file: str, class_name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ExperimentDefaults:
        """
        Parameters
        ----------
        file : str

        class_name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExperimentDefaults
            Successful Response

        Examples
        --------
        from artiq_http_client import ArtiqClient

        client = ArtiqClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.get_explist_defaults_api_explist_file_class_name_defaults_get(
            file="file",
            class_name="class_name",
        )
        """
        _response = self._raw_client.get_explist_defaults_api_explist_file_class_name_defaults_get(
            file, class_name, request_options=request_options
        )
        return _response.data

    def submit_and_wait_api_schedule_submit_and_wait_post(
        self,
        *,
        file: str,
        class_name: str,
        pipeline: typing.Optional[str] = None,
        priority: typing.Optional[int] = None,
        flush: typing.Optional[bool] = None,
        due_date: typing.Optional[float] = None,
        timeout: typing.Optional[float] = None,
        log_level: typing.Optional[int] = OMIT,
        arguments: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        repo_rev: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SubmitAndWaitResult:
        """
        Submit an experiment and wait for it to complete.

        Args:
            expid: Experiment ID specification
            pipeline: Pipeline name (default: "main")
            priority: Scheduling priority (default: 0)
            flush: Whether to flush the pipeline (default: False)
            due_date: Optional due date as Unix timestamp
            timeout: Max seconds to wait (default: 60, max: 300)

        Returns:
            SubmitAndWaitResult with rid, status, and timed_out fields

        Parameters
        ----------
        file : str

        class_name : str

        pipeline : typing.Optional[str]

        priority : typing.Optional[int]

        flush : typing.Optional[bool]

        due_date : typing.Optional[float]

        timeout : typing.Optional[float]

        log_level : typing.Optional[int]

        arguments : typing.Optional[typing.Dict[str, typing.Any]]

        repo_rev : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubmitAndWaitResult
            Successful Response

        Examples
        --------
        from artiq_http_client import ArtiqClient

        client = ArtiqClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.submit_and_wait_api_schedule_submit_and_wait_post(
            file="file",
            class_name="class_name",
        )
        """
        _response = self._raw_client.submit_and_wait_api_schedule_submit_and_wait_post(
            file=file,
            class_name=class_name,
            pipeline=pipeline,
            priority=priority,
            flush=flush,
            due_date=due_date,
            timeout=timeout,
            log_level=log_level,
            arguments=arguments,
            repo_rev=repo_rev,
            request_options=request_options,
        )
        return _response.data


def _make_default_async_client(
    timeout: typing.Optional[float],
    follow_redirects: typing.Optional[bool],
) -> httpx.AsyncClient:
    try:
        import httpx_aiohttp  # type: ignore[import-not-found]
    except ImportError:
        pass
    else:
        if follow_redirects is not None:
            return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout, follow_redirects=follow_redirects)
        return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout)

    if follow_redirects is not None:
        return httpx.AsyncClient(timeout=timeout, follow_redirects=follow_redirects)
    return httpx.AsyncClient(timeout=timeout)


class AsyncArtiqClient:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : str
        The base url to use for requests from the client.

    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from artiq_http_client import AsyncArtiqClient

    client = AsyncArtiqClient(
        base_url="https://yourhost.com/path/to/api",
    )
    """

    def __init__(
        self,
        *,
        base_url: str,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        self._client_wrapper = AsyncClientWrapper(
            base_url=base_url,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else _make_default_async_client(timeout=_defaulted_timeout, follow_redirects=follow_redirects),
            timeout=_defaulted_timeout,
            logging=logging,
        )
        self._raw_client = AsyncRawArtiqClient(client_wrapper=self._client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawArtiqClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawArtiqClient
        """
        return self._raw_client

    async def root_api_get(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from artiq_http_client import AsyncArtiqClient

        client = AsyncArtiqClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.root_api_get()


        asyncio.run(main())
        """
        _response = await self._raw_client.root_api_get(request_options=request_options)
        return _response.data

    async def get_schedule_api_schedule_get(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, ScheduleItem]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, ScheduleItem]
            Successful Response

        Examples
        --------
        import asyncio

        from artiq_http_client import AsyncArtiqClient

        client = AsyncArtiqClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.get_schedule_api_schedule_get()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_schedule_api_schedule_get(request_options=request_options)
        return _response.data

    async def submit_experiment_api_schedule_post(
        self,
        *,
        file: str,
        class_name: str,
        pipeline: typing.Optional[str] = None,
        priority: typing.Optional[int] = None,
        flush: typing.Optional[bool] = None,
        due_date: typing.Optional[float] = None,
        log_level: typing.Optional[int] = OMIT,
        arguments: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        repo_rev: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Parameters
        ----------
        file : str

        class_name : str

        pipeline : typing.Optional[str]

        priority : typing.Optional[int]

        flush : typing.Optional[bool]

        due_date : typing.Optional[float]

        log_level : typing.Optional[int]

        arguments : typing.Optional[typing.Dict[str, typing.Any]]

        repo_rev : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from artiq_http_client import AsyncArtiqClient

        client = AsyncArtiqClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.submit_experiment_api_schedule_post(
                file="file",
                class_name="class_name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.submit_experiment_api_schedule_post(
            file=file,
            class_name=class_name,
            pipeline=pipeline,
            priority=priority,
            flush=flush,
            due_date=due_date,
            log_level=log_level,
            arguments=arguments,
            repo_rev=repo_rev,
            request_options=request_options,
        )
        return _response.data

    async def get_devices_api_devices_get(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get the current device_db

        Returns:
            dict: ARTIQ Device_DB

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful Response

        Examples
        --------
        import asyncio

        from artiq_http_client import AsyncArtiqClient

        client = AsyncArtiqClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.get_devices_api_devices_get()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_devices_api_devices_get(request_options=request_options)
        return _response.data

    async def get_datasets_api_datasets_get(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Get all existing ARTIQ datasets

        This method might return a large output

        Returns:
            dict: All broadcasted ARTIQ datasets

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from artiq_http_client import AsyncArtiqClient

        client = AsyncArtiqClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.get_datasets_api_datasets_get()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_datasets_api_datasets_get(request_options=request_options)
        return _response.data

    async def get_dataset_names_api_datasets_names_get(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Get list of all dataset names (keys only)

        Returns a lightweight list of dataset names without their values,
        enabling efficient browsing and searching.

        Returns:
            dict: {"names": ["dataset1", "dataset2", ...]}

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from artiq_http_client import AsyncArtiqClient

        client = AsyncArtiqClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.get_dataset_names_api_datasets_names_get()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_dataset_names_api_datasets_names_get(request_options=request_options)
        return _response.data

    async def get_dataset_values_api_datasets_values_get(
        self, *, names: str, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Get values for specific datasets

        Args:
            names: Comma-separated list of dataset names to fetch

        Returns:
            dict: Requested datasets with their values

        Parameters
        ----------
        names : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from artiq_http_client import AsyncArtiqClient

        client = AsyncArtiqClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.get_dataset_values_api_datasets_values_get(
                names="names",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_dataset_values_api_datasets_values_get(
            names=names, request_options=request_options
        )
        return _response.data

    async def get_health_api_health_get(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Get backend health and ARTIQ connection status

        Returns:
            dict: Health status including ARTIQ connection state

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from artiq_http_client import AsyncArtiqClient

        client = AsyncArtiqClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.get_health_api_health_get()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_health_api_health_get(request_options=request_options)
        return _response.data

    async def cancel_experiment_api_cancel_post(
        self, *, rid: int, force: typing.Optional[bool] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Cancel a running experiment

        Args:
            rid (int): RID of the experiment to cancel
            force (bool): If True, forcibly close the experiment instead of requesting closure

        Parameters
        ----------
        rid : int

        force : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from artiq_http_client import AsyncArtiqClient

        client = AsyncArtiqClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.cancel_experiment_api_cancel_post(
                rid=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cancel_experiment_api_cancel_post(
            rid=rid, force=force, request_options=request_options
        )
        return _response.data

    async def get_explist_api_explist_get(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ExperimentList:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExperimentList
            Successful Response

        Examples
        --------
        import asyncio

        from artiq_http_client import AsyncArtiqClient

        client = AsyncArtiqClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.get_explist_api_explist_get()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_explist_api_explist_get(request_options=request_options)
        return _response.data

    async def get_schedule_item_api_schedule_rid_get(
        self, rid: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ScheduleItem:
        """
        Parameters
        ----------
        rid : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScheduleItem
            Successful Response

        Examples
        --------
        import asyncio

        from artiq_http_client import AsyncArtiqClient

        client = AsyncArtiqClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.get_schedule_item_api_schedule_rid_get(
                rid=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_schedule_item_api_schedule_rid_get(rid, request_options=request_options)
        return _response.data

    async def search_explist_api_explist_search_get(
        self, *, q: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> ExperimentList:
        """
        Parameters
        ----------
        q : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExperimentList
            Successful Response

        Examples
        --------
        import asyncio

        from artiq_http_client import AsyncArtiqClient

        client = AsyncArtiqClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.search_explist_api_explist_search_get()


        asyncio.run(main())
        """
        _response = await self._raw_client.search_explist_api_explist_search_get(q=q, request_options=request_options)
        return _response.data

    async def get_explist_defaults_api_explist_file_class_name_defaults_get(
        self, file: str, class_name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ExperimentDefaults:
        """
        Parameters
        ----------
        file : str

        class_name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExperimentDefaults
            Successful Response

        Examples
        --------
        import asyncio

        from artiq_http_client import AsyncArtiqClient

        client = AsyncArtiqClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.get_explist_defaults_api_explist_file_class_name_defaults_get(
                file="file",
                class_name="class_name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_explist_defaults_api_explist_file_class_name_defaults_get(
            file, class_name, request_options=request_options
        )
        return _response.data

    async def submit_and_wait_api_schedule_submit_and_wait_post(
        self,
        *,
        file: str,
        class_name: str,
        pipeline: typing.Optional[str] = None,
        priority: typing.Optional[int] = None,
        flush: typing.Optional[bool] = None,
        due_date: typing.Optional[float] = None,
        timeout: typing.Optional[float] = None,
        log_level: typing.Optional[int] = OMIT,
        arguments: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        repo_rev: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SubmitAndWaitResult:
        """
        Submit an experiment and wait for it to complete.

        Args:
            expid: Experiment ID specification
            pipeline: Pipeline name (default: "main")
            priority: Scheduling priority (default: 0)
            flush: Whether to flush the pipeline (default: False)
            due_date: Optional due date as Unix timestamp
            timeout: Max seconds to wait (default: 60, max: 300)

        Returns:
            SubmitAndWaitResult with rid, status, and timed_out fields

        Parameters
        ----------
        file : str

        class_name : str

        pipeline : typing.Optional[str]

        priority : typing.Optional[int]

        flush : typing.Optional[bool]

        due_date : typing.Optional[float]

        timeout : typing.Optional[float]

        log_level : typing.Optional[int]

        arguments : typing.Optional[typing.Dict[str, typing.Any]]

        repo_rev : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubmitAndWaitResult
            Successful Response

        Examples
        --------
        import asyncio

        from artiq_http_client import AsyncArtiqClient

        client = AsyncArtiqClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.submit_and_wait_api_schedule_submit_and_wait_post(
                file="file",
                class_name="class_name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.submit_and_wait_api_schedule_submit_and_wait_post(
            file=file,
            class_name=class_name,
            pipeline=pipeline,
            priority=priority,
            flush=flush,
            due_date=due_date,
            timeout=timeout,
            log_level=log_level,
            arguments=arguments,
            repo_rev=repo_rev,
            request_options=request_options,
        )
        return _response.data
