// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         names: "names"
 *     }
 */
export interface GetDatasetValuesApiDatasetsValuesGetRequest {
    names: string;
}
