// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         file: "file",
 *         class_name: "class_name"
 *     }
 */
export interface GetExplistDefaultsApiExplistFileClassNameDefaultsGetRequest {
    file: string;
    class_name: string;
}
