// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         rid: 1
 *     }
 */
export interface GetScheduleItemApiScheduleRidGetRequest {
    rid: number;
}
