// This file was auto-generated by Fern from our API Definition.

import type * as ArtiqhttpApi from "../../index.js";

/**
 * @example
 *     {
 *         body: {
 *             file: "file",
 *             class_name: "class_name"
 *         }
 *     }
 */
export interface SubmitExperimentApiSchedulePostRequest {
    pipeline?: string;
    priority?: number;
    flush?: boolean;
    due_date?: number;
    body: ArtiqhttpApi.ExpId;
}
