/**
 * Static-site mock adapter — lets the whole redesigned bench run as a fully
 * static site (GitHub Pages, `npx http-server dist`, ...) with **no Python
 * backend at all**.
 *
 * Activated only when `import.meta.env.VITE_MOCK === "1"` (see
 * `npm run build:mock` in package.json). Installed from `index.jsx` before
 * React renders, as a single guarded top-level import:
 *
 *   if (import.meta.env.VITE_MOCK === "1") { await import("./api/mockAdapter.js"); }
 *
 * It does two things:
 *
 * 1. Patches `window.fetch` to intercept same-origin `/api/*` requests and
 *    answer them from an in-memory store seeded from the JSON fixtures under
 *    `frontend/public/mock/` (generated by `scripts/generate_mock_fixtures.py`
 *    from `artiq_http/mock_backend.py` — see that script's docstring for the
 *    fixture-to-endpoint mapping and the `<slug>` filename encoding used by
 *    `arginfo/<slug>.json`). Every other request (including the fixture JSON
 *    itself) is passed through to the real `fetch`.
 * 2. Replaces `window.EventSource` with a shim that recognises
 *    `/api/datasets/stream/<prefix>` URLs and replays + animates the mock
 *    dataset state on a timer, reproducing sse.py's event protocol exactly
 *    (`init`/`update`/`delete`/`heartbeat`/`error`, `event.data` as a JSON
 *    string). Any other URL still gets a real `EventSource`.
 *
 * No new npm dependencies — everything here is hand-rolled against standard
 * browser APIs (fetch, Response, URL, EventTarget, MessageEvent).
 *
 * Fidelity notes:
 *  - A submitted run's lifecycle mirrors `mock_backend.py` exactly: it's
 *    inserted `pending`, flips to `running` after `SUBMIT_PENDING_DELAY_MS`
 *    and (for ndscan submissions) starts streaming points derived from the
 *    axes actually submitted, then completes and leaves the schedule once
 *    every point is in. A submission with no scan axes completes immediately
 *    as a single-point run (real ndscan 0D runs measure once and complete —
 *    see `beginZeroAxisRun`); a plain (non-ndscan) submission has no live
 *    data to stream, so it's just removed from the schedule after a short
 *    simulated run time. See IMPL-SPEC.md #17 / the mock-fidelity fix that
 *    added this — the whole point of this package is "the demo is clickable
 *    end to end".
 *  - The seeded `ndscan.rid_4823` (live) / `ndscan.rid_4821` (ghost) / `.rid_1`
 *    animations are ported line-for-line from `mock_backend.py`'s
 *    `_update_loop`: both are RabiFlop (`rabi.pulse_duration`, 101 points),
 *    matching the identity of the schedule item RID 4823 actually declares —
 *    fragment FQN, scanned axis and channel names all agree.
 *  - A freshly *submitted* scan (from this adapter, not seeded) is generic:
 *    it samples a synthetic Lorentzian bump over the actual axis/axes the
 *    user picked (1 or 2 supported, matching the session model's "max 2
 *    axes" rule) rather than trying to simulate real physics, and completes
 *    (and leaves the schedule) once its declared point total is reached, the
 *    same lifecycle a real run has.
 */

/* eslint-disable no-console */

// ── Small utilities ─────────────────────────────────────────────────────────

class MockApiError extends Error {
  constructor(status, detail) {
    super(typeof detail === "string" ? detail : JSON.stringify(detail));
    this.status = status;
    this.detail = detail;
  }
}

function jsonResponse(data, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

function gauss(mean, sigma) {
  let u = 0;
  let v = 0;
  while (u === 0) u = Math.random();
  while (v === 0) v = Math.random();
  const z = Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
  return mean + z * sigma;
}

function shuffle(arr) {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function clampByte(v) {
  return Math.max(0, Math.min(255, Math.round(v)));
}

function linspace(start, stop, n) {
  if (n <= 1) return [start];
  const out = [];
  for (let i = 0; i < n; i++) out.push(start + ((stop - start) * i) / (n - 1));
  return out;
}

/**
 * Filesystem-safe encoding of `<file>:<class_name>` used for arginfo fixture
 * filenames (`frontend/public/mock/arginfo/<slug>.json`).
 *
 * MUST exactly match `slugify()` in `scripts/generate_mock_fixtures.py` —
 * both sides need to resolve the same experiment to the same fixture file.
 */
function slugify(file, className) {
  const safeFile = file.replaceAll("/", "_").replaceAll("\\", "_");
  return `${safeFile}__${className}`;
}

// ── In-memory store ──────────────────────────────────────────────────────────

const state = {
  explist: null, // {current_rev, scanning, experiments:[...], default_revision_fallback}
  schedule: {}, // {rid: ScheduleItem}
  datasets: {}, // {key: [persist, value, metadata]}
  logs: [],
  health: null,
  nextRid: 4825,
};

const argInfoCache = new Map(); // slug -> {file, class_name, arginfo}
const activeRuns = new Map(); // rid -> RunState (submitted scans only; seeded runs animate unconditionally)
const pendingActivationTimeouts = new Map(); // rid -> timeout id (pending -> running, then data starts)
const pendingCleanupTimeouts = new Map(); // rid -> timeout id (scan -> run_done -> removed from schedule)
const pendingPlainCompletions = new Map(); // rid -> timeout id (plain experiment auto-completion)
const openEventSources = new Set(); // live MockEventSource instances, for the tick loop to push updates into

const pendingChanges = new Set();
const pendingDeletes = new Set();

function setDataset(key, value) {
  state.datasets[key] = [false, value, {}];
  pendingChanges.add(key);
  pendingDeletes.delete(key);
}

function deleteDataset(key) {
  if (key in state.datasets) {
    delete state.datasets[key];
    pendingDeletes.add(key);
    pendingChanges.delete(key);
  }
}

function getDatasetsForPrefix(prefix) {
  const out = {};
  for (const [k, v] of Object.entries(state.datasets)) {
    if (k === prefix || k.startsWith(`${prefix}.`)) out[k] = v;
  }
  return out;
}

// ── Fixture loading ──────────────────────────────────────────────────────────

// import.meta.env.BASE_URL always ends with "/" (e.g. "/", "/artiq_http/",
// "/artiq_http/pr-12/") — fixtures live under `<base>mock/...` in the built
// site, mirroring frontend/public/mock/ at dev time.
const MOCK_BASE = `${import.meta.env.BASE_URL}mock/`;

let realFetchRef = null;

async function fetchFixture(name) {
  const fetcher = realFetchRef || window.fetch;
  const res = await fetcher(MOCK_BASE + name);
  if (!res.ok) {
    throw new Error(
      `mockAdapter: failed to load fixture ${name}: ${res.status} ${res.statusText}`,
    );
  }
  return res.json();
}

let loadPromise = null;

function ensureLoaded() {
  if (loadPromise) return loadPromise;
  loadPromise = (async () => {
    const [explist, schedule, datasets, health, logs] = await Promise.all([
      fetchFixture("explist.json"),
      fetchFixture("schedule.json"),
      fetchFixture("datasets.json"),
      fetchFixture("health.json"),
      fetchFixture("logs.json"),
    ]);
    state.explist = explist;
    state.schedule = schedule;
    state.datasets = datasets;
    state.health = health;
    state.logs = logs.logs || [];
    state.nextRid = 4825;
  })();
  return loadPromise;
}

async function loadArginfoFixture(file, className) {
  const slug = slugify(file, className);
  if (argInfoCache.has(slug)) return argInfoCache.get(slug);
  try {
    const doc = await fetchFixture(`arginfo/${slug}.json`);
    argInfoCache.set(slug, doc);
    return doc;
  } catch (err) {
    console.warn("[mockAdapter] could not load arginfo fixture", slug, err);
    return null;
  }
}

function findExplistEntry(file, className) {
  return (
    (state.explist?.experiments || []).find(
      (e) => e.file === file && e.class_name === className,
    ) || null
  );
}

function findExplistArginfoSync(file, className) {
  const entry = findExplistEntry(file, className);
  return entry ? (entry.arginfo ?? null) : null;
}

// ── ndscan wire-format ports (mirrors artiq_http/artiq_api/ndscan_builder.py
//    and ndscan_validation.py — see those modules for the authoritative
//    Python implementation this is kept in sync with by hand) ───────────────

function extractNdscanDefault(arginfo) {
  const ndscanParams = arginfo?.ndscan_params;
  if (!ndscanParams || !Array.isArray(ndscanParams)) return {};
  try {
    const spec = ndscanParams[0];
    if (!spec || typeof spec !== "object") return {};
    const defaultJson = spec.default;
    if (typeof defaultJson !== "string") return {};
    const parsed = JSON.parse(defaultJson);
    return parsed && typeof parsed === "object" ? parsed : {};
  } catch {
    return {};
  }
}

function extractSchemataFromArginfo(arginfo) {
  const s = extractNdscanDefault(arginfo).schemata;
  return s && typeof s === "object" ? s : {};
}

function extractInstancesFromArginfo(arginfo) {
  const i = extractNdscanDefault(arginfo).instances;
  return i && typeof i === "object" ? i : {};
}

function invertInstances(instances) {
  const map = {};
  for (const [path, fqns] of Object.entries(instances || {})) {
    if (!Array.isArray(fqns)) continue;
    for (const fqn of fqns) {
      const list = map[fqn] || (map[fqn] = []);
      if (!list.includes(path)) list.push(path);
    }
  }
  return map;
}

function resolvePath(fqn, explicitPath, fqnToPaths) {
  const candidates = fqnToPaths[fqn];
  if (explicitPath != null) {
    if (candidates && !candidates.includes(explicitPath)) {
      throw new MockApiError(
        422,
        `explicit path '${explicitPath}' for '${fqn}' is not one of its instance paths ${JSON.stringify(
          candidates,
        )}`,
      );
    }
    return explicitPath;
  }
  if (!candidates || candidates.length === 0) return "";
  if (candidates.length === 1) return candidates[0];
  throw new MockApiError(
    422,
    `parameter '${fqn}' exists at multiple instance paths ${JSON.stringify(
      candidates,
    )}; specify the path explicitly to disambiguate`,
  );
}

function splitFixedParam(value) {
  if (
    value &&
    typeof value === "object" &&
    !Array.isArray(value) &&
    "value" in value
  ) {
    return [value.value, value.path ?? null];
  }
  return [value, null];
}

const SUPPORTED_GENERATORS = {
  linear: ["start", "stop", "num_points"],
  centre_span: ["centre", "half_span", "num_points"],
  list: ["values"],
};

function buildAxis(axis, fqnToPaths) {
  const fqn = axis?.fqn;
  if (!fqn || typeof fqn !== "string")
    throw new MockApiError(422, "scan axis missing 'fqn'");
  const gtype = axis.type;
  if (!(gtype in SUPPORTED_GENERATORS)) {
    throw new MockApiError(
      422,
      `invalid scan type '${gtype}'. Must be one of: ${Object.keys(
        SUPPORTED_GENERATORS,
      )
        .sort()
        .join(", ")}`,
    );
  }
  const rangeIn = axis.range;
  if (!rangeIn || typeof rangeIn !== "object") {
    throw new MockApiError(
      422,
      `scan axis '${fqn}' missing or invalid 'range'`,
    );
  }
  const required = SUPPORTED_GENERATORS[gtype];
  const missing = required.filter((k) => !(k in rangeIn));
  if (missing.length) {
    throw new MockApiError(
      422,
      `scan axis '${fqn}' (${gtype}) range missing keys: ${missing.join(", ")}`,
    );
  }
  const rangeOut = { ...rangeIn };
  if (rangeOut.randomise_order === undefined) rangeOut.randomise_order = false;
  const path = resolvePath(fqn, axis.path ?? null, fqnToPaths);
  return { type: gtype, range: rangeOut, fqn, path };
}

function buildNdscanParamsFromArginfo(
  arginfo,
  file,
  className,
  axes,
  fixedParams,
  numRepeats,
) {
  const schemata = extractSchemataFromArginfo(arginfo);
  if (!schemata || Object.keys(schemata).length === 0) {
    throw new MockApiError(
      422,
      `Experiment ${file}/${className} has no ndscan schemata`,
    );
  }
  const fqnToPaths = invertInstances(extractInstancesFromArginfo(arginfo));

  const overrides = {};
  for (const [fqn, raw] of Object.entries(fixedParams || {})) {
    const [value, explicitPath] = splitFixedParam(raw);
    const path = resolvePath(fqn, explicitPath, fqnToPaths);
    overrides[fqn] = [{ path, value }];
  }

  const paramsData = {
    overrides,
    scan: {
      axes: (axes || []).map((ax) => buildAxis(ax, fqnToPaths)),
      num_repeats: numRepeats,
      no_axes_mode: "single",
      randomise_order_globally: false,
    },
  };
  return JSON.stringify(paramsData);
}

function getNdscanJson(argumentsObj) {
  const v = argumentsObj?.ndscan_params;
  if (v == null) return [null, null];
  if (typeof v === "string") return [v, null];
  if (Array.isArray(v) && v.length) {
    const spec = v[0];
    if (spec && typeof spec === "object" && typeof spec.default === "string")
      return [spec.default, null];
  }
  return [
    null,
    "ndscan_params must be a PYON/JSON string (or [spec, None, None] triple)",
  ];
}

const VALID_SCAN_TYPES = new Set(["linear", "centre_span", "list"]);
const RANGE_KEYS = {
  linear: ["start", "stop", "num_points"],
  centre_span: ["centre", "half_span", "num_points"],
  list: ["values"],
};

function validateAxis(axis, canonicalFqns, idx) {
  if (!axis || typeof axis !== "object")
    return `scan.axes[${idx}] is not a dict`;
  const fqn = axis.fqn;
  if (!fqn || typeof fqn !== "string")
    return `scan.axes[${idx}]: missing or invalid 'fqn'`;
  if (canonicalFqns.size && !canonicalFqns.has(fqn))
    return `scan.axes[${idx}]: unknown parameter '${fqn}'`;
  if (!("path" in axis)) return `scan.axes[${idx}]: missing 'path'`;
  const scanType = axis.type;
  if (!scanType || !VALID_SCAN_TYPES.has(scanType)) {
    return `scan.axes[${idx}]: invalid scan type '${scanType}'. Must be one of: ${[
      ...VALID_SCAN_TYPES,
    ]
      .sort()
      .join(", ")}`;
  }
  const rangeData = axis.range;
  if (!rangeData || typeof rangeData !== "object")
    return `scan.axes[${idx}]: missing or invalid 'range'`;
  const missing = RANGE_KEYS[scanType].filter((k) => !(k in rangeData));
  if (missing.length)
    return `scan.axes[${idx}]: range missing ${missing.join(", ")}`;

  if (scanType === "list") {
    const values = rangeData.values;
    if (!Array.isArray(values) || values.length === 0) {
      return `scan.axes[${idx}]: list scan requires a non-empty 'values' list`;
    }
    return null;
  }

  const numericKeys = RANGE_KEYS[scanType].slice(0, -1);
  for (const k of numericKeys) {
    if (!Number.isFinite(Number(rangeData[k])))
      return `scan.axes[${idx}]: range values must be numeric`;
  }
  const numPoints = Number(rangeData.num_points);
  if (!Number.isInteger(numPoints))
    return `scan.axes[${idx}]: range values must be numeric`;
  if (numPoints <= 0)
    return `scan.axes[${idx}]: num_points (${numPoints}) must be greater than 0`;
  if (scanType === "linear" && numPoints < 2)
    return `scan.axes[${idx}]: linear scan needs num_points >= 2`;
  if (
    scanType === "linear" &&
    Number(rangeData.start) === Number(rangeData.stop)
  ) {
    return `scan.axes[${idx}]: linear scan start and stop must differ`;
  }
  return null;
}

function validateOverrides(overrides) {
  if (!overrides || typeof overrides !== "object" || Array.isArray(overrides)) {
    return "ndscan_params 'overrides' must be a dict";
  }
  for (const [fqn, specs] of Object.entries(overrides)) {
    if (!Array.isArray(specs) || specs.length === 0) {
      return `override for '${fqn}' must be a non-empty list of path/value specs`;
    }
    for (const spec of specs) {
      if (
        !spec ||
        typeof spec !== "object" ||
        !("path" in spec) ||
        !("value" in spec)
      ) {
        return `override for '${fqn}' must contain dicts with 'path' and 'value'`;
      }
    }
  }
  return null;
}

/** Port of ndscan_validation.validate_ndscan_params. Returns an error string or null. */
function validateNdscanParamsArguments(argumentsObj, arginfo) {
  const [jsonString, err] = getNdscanJson(argumentsObj);
  if (err) return err;
  if (jsonString == null) return null;

  let paramsData;
  try {
    paramsData = JSON.parse(jsonString);
  } catch (e) {
    return `ndscan_params JSON parse error: ${e.message}`;
  }
  if (!paramsData || typeof paramsData !== "object")
    return "ndscan_params JSON must parse to a dict";
  if (!("scan" in paramsData))
    return "ndscan_params missing required key 'scan'";
  const scan = paramsData.scan;
  if (!scan || typeof scan !== "object")
    return "ndscan_params 'scan' must be a dict";
  const axes = scan.axes ?? [];
  if (!Array.isArray(axes)) return "ndscan_params 'scan.axes' must be a list";

  let canonicalFqns = new Set();
  if (arginfo != null)
    canonicalFqns = new Set(Object.keys(extractSchemataFromArginfo(arginfo)));

  const scannedFqns = new Set();
  for (let idx = 0; idx < axes.length; idx++) {
    const e = validateAxis(axes[idx], canonicalFqns, idx);
    if (e) return e;
    scannedFqns.add(axes[idx].fqn);
  }

  const overrides = paramsData.overrides ?? {};
  const errO = validateOverrides(overrides);
  if (errO) return errO;
  for (const fqn of Object.keys(overrides)) {
    if (canonicalFqns.size && !canonicalFqns.has(fqn))
      return `override references unknown parameter '${fqn}'`;
    if (scannedFqns.has(fqn))
      return `parameter '${fqn}' is both scanned and fixed (in overrides)`;
  }

  const numRepeats = scan.num_repeats ?? 1;
  if (!Number.isInteger(numRepeats) || numRepeats < 1) {
    return `scan.num_repeats (${numRepeats}) must be an integer >= 1`;
  }
  return null;
}

// ── extract_arginfo_defaults / _filter_ndscan_always_shown ports (notifiers.py) ──

function parseNdscanDefaultValue(typeStr, defaultStr) {
  if (typeStr === "bool") return String(defaultStr).toLowerCase() === "true";
  if (typeStr === "float") return parseFloat(defaultStr);
  if (typeStr === "int") {
    const n = parseInt(defaultStr, 10);
    return Number.isNaN(n) ? parseFloat(defaultStr) : n;
  }
  return defaultStr;
}

function extractNdscanDefaults(arginfo) {
  const schemata = extractSchemataFromArginfo(arginfo);
  const defaults = {};
  for (const [fqn, schema] of Object.entries(schemata)) {
    if (!schema || typeof schema !== "object") continue;
    const paramName = fqn.split(".").pop();
    const defaultValue = schema.default;
    if (defaultValue != null) {
      defaults[paramName] = parseNdscanDefaultValue(
        schema.type ?? "str",
        defaultValue,
      );
    }
  }
  return defaults;
}

function extractArginfoDefaults(arginfo) {
  const defaults = {};
  if (arginfo && "ndscan_params" in arginfo) {
    Object.assign(defaults, extractNdscanDefaults(arginfo));
  }
  for (const [argName, argData] of Object.entries(arginfo || {})) {
    if (!Array.isArray(argData) || argData.length < 2) continue;
    const [typeStr, specDict] = argData;
    if (!specDict || typeof specDict !== "object") continue;
    if (
      [
        "NumberValue",
        "StringValue",
        "BooleanValue",
        "EnumerationValue",
        "Scannable",
      ].includes(typeStr)
    ) {
      if ("default" in specDict) defaults[argName] = specDict.default;
    }
  }
  return defaults;
}

function filterNdscanAlwaysShown(arginfo) {
  if (!arginfo || !("ndscan_params" in arginfo)) return arginfo;
  const ndscanParams = arginfo.ndscan_params;
  if (!ndscanParams || !Array.isArray(ndscanParams)) return arginfo;
  try {
    const spec = ndscanParams[0];
    if (!spec || typeof spec !== "object") return arginfo;
    const defaultJson = spec.default;
    if (typeof defaultJson !== "string") return arginfo;
    const paramsData = JSON.parse(defaultJson);
    const alwaysShown = paramsData.always_shown ?? [];

    const alwaysShownFqns = new Set();
    for (const item of alwaysShown) {
      if (item && typeof item === "object" && "__jsonclass__" in item) {
        const jc = item.__jsonclass__;
        if (Array.isArray(jc) && jc.length === 2) {
          const tupleData = jc[1];
          if (Array.isArray(tupleData) && tupleData.length > 0) {
            const inner = tupleData[0];
            if (Array.isArray(inner) && inner.length > 0)
              alwaysShownFqns.add(inner[0]);
          }
        }
      } else if (Array.isArray(item) && item.length > 0) {
        alwaysShownFqns.add(item[0]);
      }
    }

    if (alwaysShownFqns.size === 0) {
      const result = { ...arginfo };
      delete result.ndscan_params;
      return result;
    }

    const schemata = paramsData.schemata ?? {};
    paramsData.schemata = Object.fromEntries(
      Object.entries(schemata).filter(([fqn]) => alwaysShownFqns.has(fqn)),
    );

    const instances = paramsData.instances ?? {};
    const filteredInstances = {};
    for (const [key, fqns] of Object.entries(instances)) {
      const kept = (fqns || []).filter((fqn) => alwaysShownFqns.has(fqn));
      if (kept.length) filteredInstances[key] = kept;
    }
    paramsData.instances = filteredInstances;

    return {
      ...arginfo,
      ndscan_params: [
        { ty: spec.ty ?? "PYONValue", default: JSON.stringify(paramsData) },
        null,
        null,
      ],
    };
  } catch {
    return arginfo;
  }
}

// ── Explist / arginfo / defaults / recompute handlers ────────────────────────

function parseFields(fieldsParam) {
  return (fieldsParam ?? "name,file,class_name,docstring")
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
}

function projectEntry(exp, fields, full) {
  const wanted = new Set(fields);
  const out = {
    name: exp.name,
    file: exp.file,
    class_name: exp.class_name,
    arginfo: wanted.has("arginfo") ? (exp.arginfo ?? null) : null,
    argument_ui: wanted.has("argument_ui") ? (exp.argument_ui ?? null) : null,
    scheduler_defaults: wanted.has("scheduler_defaults")
      ? (exp.scheduler_defaults ?? null)
      : null,
    docstring: wanted.has("docstring") ? (exp.docstring ?? null) : null,
  };
  if (out.arginfo && !full) out.arginfo = filterNdscanAlwaysShown(out.arginfo);
  return out;
}

function handleGetExplist(url) {
  const fields = parseFields(url.searchParams.get("fields"));
  const full = url.searchParams.get("full") === "true";
  return {
    current_rev: state.explist.current_rev,
    scanning: state.explist.scanning,
    experiments: state.explist.experiments.map((e) =>
      projectEntry(e, fields, full),
    ),
    default_revision_fallback: state.explist.default_revision_fallback,
  };
}

function handleSearchExplist(url) {
  const q = url.searchParams.get("q") ?? "";
  const fields = parseFields(url.searchParams.get("fields"));
  const full = url.searchParams.get("full") === "true";
  let exps = state.explist.experiments;
  if (q) {
    const ql = q.toLowerCase();
    exps = exps.filter(
      (e) =>
        e.name.toLowerCase().includes(ql) ||
        e.file.toLowerCase().includes(ql) ||
        e.class_name.toLowerCase().includes(ql),
    );
  }
  return {
    current_rev: state.explist.current_rev,
    scanning: state.explist.scanning,
    experiments: exps.map((e) => projectEntry(e, fields, full)),
    default_revision_fallback: state.explist.default_revision_fallback,
  };
}

async function handleGetArginfo(file, className) {
  const entry = findExplistEntry(file, className);
  if (!entry)
    throw new MockApiError(404, `Experiment ${file}/${className} not found`);
  const doc = await loadArginfoFixture(file, className);
  const arginfo = doc?.arginfo ?? entry.arginfo ?? {};
  return { file, class_name: className, arginfo };
}

async function handleDefaults(file, className) {
  const entry = findExplistEntry(file, className);
  if (!entry)
    throw new MockApiError(404, `Experiment ${file}/${className} not found`);
  const doc = await loadArginfoFixture(file, className);
  const arginfo = doc?.arginfo ?? entry.arginfo ?? {};
  return {
    file,
    class_name: className,
    arguments: extractArginfoDefaults(arginfo),
  };
}

// ── Schedule / submission ─────────────────────────────────────────────────────

const INFINITE_REPEATS = 2147483647;
const MAX_DEMO_POINTS = 4000;
const POINTS_PER_TICK_TARGET_TICKS = 40;
const RUN_CLEANUP_DELAY_MS = 4000;
const PLAIN_RUN_DURATION_MS = 4000;
// Mirrors mock_backend.py's _SUBMIT_PENDING_DELAY_S: a submission sits
// `pending` for this long before flipping to `running` and starting to
// stream data, so both mocks show the same realistic queue -> live lifecycle
// instead of a run appearing "running" the instant it's submitted.
const SUBMIT_PENDING_DELAY_MS = 2000;

const GENERIC_SCAN_CHANNELS = {
  signal: {
    path: "signal",
    description: "Excitation",
    type: "float",
    scale: 1.0,
    unit: "",
  },
  reference: {
    path: "reference",
    description: "Reference",
    type: "float",
    scale: 1.0,
    unit: "",
    display_hints: { priority: -1 },
  },
  atom_number: {
    path: "atom_number",
    description: "Atom number",
    type: "float",
    scale: 1.0,
    unit: "",
  },
};

function allocateRid() {
  const rid = state.nextRid;
  state.nextRid += 1;
  return rid;
}

function normaliseExpId(body) {
  if (
    !body ||
    typeof body.file !== "string" ||
    typeof body.class_name !== "string"
  ) {
    throw new MockApiError(
      422,
      "Invalid ExpID: 'file' and 'class_name' are required",
    );
  }
  return {
    log_level: Number.isFinite(body.log_level) ? body.log_level : 30,
    file: body.file,
    class_name: body.class_name,
    arguments: body.arguments == null ? {} : body.arguments,
    repo_rev: body.repo_rev ?? null,
  };
}

function deriveFragmentFqn(file, className) {
  const modulePath = file.replace(/\.py$/, "").replaceAll("/", ".");
  return `${modulePath}.${className}`;
}

function axisPointValues(axisWire) {
  const { type, range } = axisWire;
  if (type === "list") return (range.values || []).slice();
  if (type === "linear")
    return linspace(range.start, range.stop, range.num_points);
  if (type === "centre_span") {
    return linspace(
      range.centre - range.half_span,
      range.centre + range.half_span,
      range.num_points,
    );
  }
  return [0];
}

function axisDescriptorForDataset(axisWire, arginfo, values) {
  const min = Math.min(...values);
  const max = Math.max(...values);
  const increment = values.length > 1 ? (max - min) / (values.length - 1) : 0;
  const schema = extractSchemataFromArginfo(arginfo)[axisWire.fqn];
  const param = schema
    ? { ...schema, unit: schema.spec?.unit ?? "" }
    : {
        default: "0",
        description: axisWire.fqn,
        fqn: axisWire.fqn,
        unit: "",
        type: "float",
        spec: { is_scannable: true, scale: 1 },
      };
  if (!param.fqn) param.fqn = axisWire.fqn;
  return { increment, max, min, path: axisWire.path ?? "*", param };
}

function cartesianProduct(valueArrays) {
  return valueArrays.reduce(
    (acc, values) => {
      const out = [];
      for (const prefixPt of acc)
        for (const v of values) out.push([...prefixPt, v]);
      return out;
    },
    [[]],
  );
}

function buildShuffledPlan(grid, repeats) {
  const plan = [];
  for (let r = 0; r < repeats; r++) for (const pt of grid) plan.push(pt);
  return shuffle(plan);
}

function sampleChannelsGeneric(pt, center, axisSpans) {
  let distSq = 0;
  for (let i = 0; i < pt.length; i++) {
    const [lo, hi] = axisSpans[i];
    const span = hi - lo || 1;
    const norm = (pt[i] - center[i]) / (span * 0.25);
    distSq += norm * norm;
  }
  const bump = 1 / (1 + distSq);
  return {
    signal: 0.12 + 0.8 * bump + gauss(0, 0.05),
    reference: 0.5 + gauss(0, 0.03),
    atom_number: Math.max(0, 50000 + 30000 * bump + gauss(0, 3000)),
  };
}

function beginZeroAxisRun(rid, prefix, fragmentFqn) {
  // No scanned axes: a real ndscan 0D run measures once and completes
  // immediately (NoAxisRunner in ndscan/experiment/entry_point.py), so this
  // publishes one point and completes rather than ticking forever like the
  // always-live 0D repeat demo (ndscan.rid_1) does.
  setDataset(`${prefix}.axes`, "[]");
  setDataset(`${prefix}.channels`, JSON.stringify(GENERIC_SCAN_CHANNELS));
  setDataset(`${prefix}.fragment_fqn`, fragmentFqn);
  setDataset(`${prefix}.point.signal`, 0.5 + gauss(0, 0.05));
  setDataset(`${prefix}.point.reference`, 0.5 + gauss(0, 0.03));
  setDataset(
    `${prefix}.point.atom_number`,
    Math.max(0, 50000 + gauss(0, 3000)),
  );
  setDataset(`${prefix}.completed`, true);
  finishRun(rid, prefix);
}

function beginNdscanRun(rid, expid, axesWire, numRepeatsRaw, arginfo) {
  const prefix = `ndscan.rid_${rid}`;
  const fragmentFqn = deriveFragmentFqn(expid.file, expid.class_name);

  if (!axesWire || axesWire.length === 0) {
    beginZeroAxisRun(rid, prefix, fragmentFqn);
    return;
  }

  const valueArrays = axesWire.map(axisPointValues);
  const descriptors = axesWire.map((ax, i) =>
    axisDescriptorForDataset(ax, arginfo, valueArrays[i]),
  );
  setDataset(`${prefix}.axes`, JSON.stringify(descriptors));
  setDataset(`${prefix}.channels`, JSON.stringify(GENERIC_SCAN_CHANNELS));
  setDataset(`${prefix}.fragment_fqn`, fragmentFqn);
  setDataset(`${prefix}.completed`, false);
  for (let i = 0; i < axesWire.length; i++)
    setDataset(`${prefix}.points.axis_${i}`, []);
  for (const key of Object.keys(GENERIC_SCAN_CHANNELS))
    setDataset(`${prefix}.points.channel_${key}`, []);

  const grid = cartesianProduct(valueArrays);
  const gridSize = grid.length;
  const numRepeats = Number.isFinite(numRepeatsRaw) ? numRepeatsRaw : 1;
  const isInfinite =
    numRepeats === INFINITE_REPEATS || !Number.isFinite(numRepeats);
  const finiteTotal = isInfinite ? null : gridSize * Math.max(1, numRepeats);
  const loopForever =
    isInfinite || gridSize === 0 || finiteTotal > MAX_DEMO_POINTS;

  const center = valueArrays.map(
    (vals) => vals[Math.floor(vals.length * 0.4)] ?? vals[0] ?? 0,
  );
  const run = {
    rid,
    prefix,
    numAxes: axesWire.length,
    grid,
    center,
    axisSpans: valueArrays.map((vals) => [
      Math.min(...vals),
      Math.max(...vals),
    ]),
    loopForever,
    plan: buildShuffledPlan(grid, loopForever ? 1 : Math.max(1, numRepeats)),
    idx: 0,
    done: false,
  };
  run.pointsPerTick = Math.max(
    1,
    Math.ceil(run.plan.length / POINTS_PER_TICK_TARGET_TICKS),
  );
  activeRuns.set(rid, run);
}

function appendPoint(run, pt) {
  for (let i = 0; i < run.numAxes; i++) {
    const arr = (
      state.datasets[`${run.prefix}.points.axis_${i}`]?.[1] ?? []
    ).slice();
    arr.push(pt[i]);
    setDataset(`${run.prefix}.points.axis_${i}`, arr);
  }
  const sample = sampleChannelsGeneric(pt, run.center, run.axisSpans);
  for (const [key, value] of Object.entries(sample)) {
    const arr = (
      state.datasets[`${run.prefix}.points.channel_${key}`]?.[1] ?? []
    ).slice();
    arr.push(value);
    setDataset(`${run.prefix}.points.channel_${key}`, arr);
  }
}

function resetRunPoints(run) {
  for (let i = 0; i < run.numAxes; i++)
    setDataset(`${run.prefix}.points.axis_${i}`, []);
  for (const key of Object.keys(GENERIC_SCAN_CHANNELS))
    setDataset(`${run.prefix}.points.channel_${key}`, []);
}

function nudgeCenter(run) {
  run.center = run.center.map((c, i) => {
    const [lo, hi] = run.axisSpans[i];
    const span = hi - lo || 1;
    return Math.max(
      lo,
      Math.min(hi, c + (Math.random() * 2 - 1) * span * 0.15),
    );
  });
}

// Marks *rid*'s dataset completed and its schedule item `run_done`, then
// removes it from the schedule after a short delay — mirroring a real ARTIQ
// master dropping a finished run off the queue. Shared by ndscan run
// completion (completeRun) and the one-shot zero-axis path (beginZeroAxisRun).
function finishRun(rid, prefix) {
  activeRuns.delete(rid);
  setDataset(`${prefix}.completed`, true);
  const item = state.schedule[rid];
  if (item) item.status = "run_done";
  const t = setTimeout(() => {
    pendingCleanupTimeouts.delete(rid);
    delete state.schedule[rid];
  }, RUN_CLEANUP_DELAY_MS);
  pendingCleanupTimeouts.set(rid, t);
}

function completeRun(run) {
  run.done = true;
  finishRun(run.rid, run.prefix);
}

function tickNdscanRun(run) {
  if (run.done) return;
  let remaining = run.pointsPerTick;
  while (remaining > 0) {
    if (run.idx >= run.plan.length) {
      if (run.loopForever) {
        run.plan = buildShuffledPlan(run.grid, 1);
        run.idx = 0;
        nudgeCenter(run);
        resetRunPoints(run);
      } else {
        completeRun(run);
        return;
      }
    }
    if (run.idx >= run.plan.length) return; // defensive: empty grid
    appendPoint(run, run.plan[run.idx++]);
    remaining--;
  }
}

function startRunFromExpid(rid, expid) {
  const [raw] = getNdscanJson(expid.arguments || {});
  if (typeof raw !== "string") {
    // Plain (non-ndscan) experiment: nothing to stream. Simulate a quick job
    // rather than leaving a "running" item stuck forever with no live data.
    const t = setTimeout(() => {
      pendingPlainCompletions.delete(rid);
      delete state.schedule[rid];
    }, PLAIN_RUN_DURATION_MS);
    pendingPlainCompletions.set(rid, t);
    return;
  }
  let parsed;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return;
  }
  const axes = parsed?.scan?.axes ?? [];
  const numRepeats = parsed?.scan?.num_repeats ?? 1;
  const arginfo = findExplistArginfoSync(expid.file, expid.class_name);
  beginNdscanRun(rid, expid, axes, numRepeats, arginfo);
}

function insertScheduleItem(rid, item) {
  state.schedule[rid] = item;
}

// Mirrors mock_backend.py's _activate_submission: after the pending delay,
// flip *rid* to `running` and start its data (unless it was cancelled, or
// its status was otherwise changed, in the meantime).
function scheduleActivation(rid) {
  const t = setTimeout(() => {
    pendingActivationTimeouts.delete(rid);
    const item = state.schedule[rid];
    if (!item || item.status !== "pending") return;
    item.status = "running";
    startRunFromExpid(rid, item.expid);
  }, SUBMIT_PENDING_DELAY_MS);
  pendingActivationTimeouts.set(rid, t);
}

function mockWaitForCompletion(rid, timeoutSeconds) {
  // The mock has no real notion of "finished" on a fixed timeline, so this
  // resolves after a short bounded delay rather than genuinely waiting up to
  // `timeoutSeconds` — good enough to exercise the wait_for_completion=True
  // code path without hanging a demo page.
  const waitMs = Math.min(3000, Math.max(500, timeoutSeconds * 1000));
  return new Promise((resolve) => {
    setTimeout(
      () =>
        resolve({ rid, status: "completed", timed_out: false, error: null }),
      waitMs,
    );
  });
}

function handleSubmitExperiment(url, body) {
  const pipeline = url.searchParams.get("pipeline") ?? "main";
  const priority = Number(url.searchParams.get("priority") ?? "0");
  const flush = (url.searchParams.get("flush") ?? "false") === "true";
  const dueDateRaw = url.searchParams.get("due_date");
  const dueDate =
    dueDateRaw != null && dueDateRaw !== "" ? Number(dueDateRaw) : null;
  const waitForCompletion =
    (url.searchParams.get("wait_for_completion") ?? "false") === "true";
  const timeout = Number(url.searchParams.get("timeout") ?? "600");

  const expid = normaliseExpId(body);
  if (expid.arguments && "ndscan_params" in expid.arguments) {
    const arginfo = findExplistArginfoSync(expid.file, expid.class_name);
    const err = validateNdscanParamsArguments(expid.arguments, arginfo);
    if (err) throw new MockApiError(422, err);
  }

  const rid = allocateRid();
  insertScheduleItem(rid, {
    pipeline,
    priority,
    due_date: dueDate,
    flush,
    status: "pending",
    repo_msg: null,
    expid,
  });
  scheduleActivation(rid);

  if (waitForCompletion) return mockWaitForCompletion(rid, timeout);
  return rid;
}

function handleSubmitScan(url, body) {
  const waitForCompletion =
    (url.searchParams.get("wait_for_completion") ?? "false") === "true";
  const timeout = Number(url.searchParams.get("timeout") ?? "600");

  if (
    !body ||
    typeof body.file !== "string" ||
    typeof body.class_name !== "string" ||
    !Array.isArray(body.axes)
  ) {
    throw new MockApiError(
      422,
      "Invalid ScanSubmitRequest: 'file', 'class_name', and 'axes' are required",
    );
  }
  const { file, class_name: className } = body;
  const arginfo = findExplistArginfoSync(file, className);
  if (!arginfo)
    throw new MockApiError(
      404,
      `Experiment ${file}/${className} not found in explist`,
    );

  const ndscanParams = buildNdscanParamsFromArginfo(
    arginfo,
    file,
    className,
    body.axes,
    body.fixed_params,
    body.num_repeats ?? 1,
  );

  const argumentsObj = { ndscan_params: ndscanParams };
  const err = validateNdscanParamsArguments(argumentsObj, arginfo);
  if (err) throw new MockApiError(422, err);

  const expid = {
    log_level: 30,
    file,
    class_name: className,
    arguments: argumentsObj,
    repo_rev: body.repo_rev ?? null,
  };
  const rid = allocateRid();
  insertScheduleItem(rid, {
    pipeline: body.pipeline ?? "main",
    priority: body.priority ?? 0,
    due_date: body.due_date ?? null,
    flush: !!body.flush,
    status: "pending",
    repo_msg: null,
    expid,
  });
  scheduleActivation(rid);

  if (waitForCompletion) return mockWaitForCompletion(rid, timeout);
  return rid;
}

function handleCancel(url) {
  const rid = Number(url.searchParams.get("rid"));
  if (!Number.isFinite(rid) || !(rid in state.schedule)) {
    throw new MockApiError(404, `RID ${rid} not found in schedule`);
  }
  delete state.schedule[rid];

  const run = activeRuns.get(rid);
  if (run) {
    run.done = true;
    activeRuns.delete(rid);
    setDataset(`${run.prefix}.completed`, true);
  }
  const activationT = pendingActivationTimeouts.get(rid);
  if (activationT) {
    clearTimeout(activationT);
    pendingActivationTimeouts.delete(rid);
  }
  const cleanupT = pendingCleanupTimeouts.get(rid);
  if (cleanupT) {
    clearTimeout(cleanupT);
    pendingCleanupTimeouts.delete(rid);
  }
  const plainT = pendingPlainCompletions.get(rid);
  if (plainT) {
    clearTimeout(plainT);
    pendingPlainCompletions.delete(rid);
  }
  return null;
}

// ── Logs / health ──────────────────────────────────────────────────────────

function handleGetLogs(url) {
  const sourceRegex = url.searchParams.get("source_regex");
  const messageRegex = url.searchParams.get("message_regex");
  const minLevel = url.searchParams.get("min_level");
  const maxLevel = url.searchParams.get("max_level");
  const since = url.searchParams.get("since");
  const until = url.searchParams.get("until");
  const limit = url.searchParams.get("limit");

  let sourceRe = null;
  let messageRe = null;
  try {
    if (sourceRegex) sourceRe = new RegExp(sourceRegex);
  } catch (e) {
    throw new MockApiError(400, `Invalid regex for source_regex: ${e.message}`);
  }
  try {
    if (messageRegex) messageRe = new RegExp(messageRegex);
  } catch (e) {
    throw new MockApiError(
      400,
      `Invalid regex for message_regex: ${e.message}`,
    );
  }

  let entries = state.logs.filter((e) => {
    if (minLevel != null && (e.level ?? -Infinity) < Number(minLevel))
      return false;
    if (maxLevel != null && (e.level ?? Infinity) > Number(maxLevel))
      return false;
    if (since != null && (e.timestamp ?? Infinity) < Number(since))
      return false;
    if (until != null && (e.timestamp ?? -Infinity) > Number(until))
      return false;
    if (sourceRe && !sourceRe.test(String(e.source ?? ""))) return false;
    if (messageRe && !messageRe.test(String(e.message ?? ""))) return false;
    return true;
  });
  if (limit != null) entries = entries.slice(0, Number(limit));
  return { logs: entries };
}

// ── Route table ──────────────────────────────────────────────────────────────

async function routeApi(method, url, body) {
  await ensureLoaded();
  const segs = url.pathname.split("/").filter(Boolean);
  if (segs[0] !== "api") throw new MockApiError(404, "Not Found");
  const rest = segs.slice(1);

  if (rest.length === 0) {
    if (method === "GET") return { message: "Hello World" };
    throw new MockApiError(405, "Method Not Allowed");
  }

  if (rest[0] === "explist") {
    if (rest.length === 1) {
      if (method === "GET") return handleGetExplist(url);
      throw new MockApiError(405, "Method Not Allowed");
    }
    if (rest[1] === "search") {
      if (method === "GET") return handleSearchExplist(url);
      throw new MockApiError(405, "Method Not Allowed");
    }
    if (rest.length >= 4) {
      const suffix = rest[rest.length - 1];
      const className = decodeURIComponent(rest[rest.length - 2]);
      const file = rest
        .slice(1, rest.length - 2)
        .map(decodeURIComponent)
        .join("/");
      if (suffix === "arginfo" && method === "GET")
        return handleGetArginfo(file, className);
      if (suffix === "defaults" && method === "GET")
        return handleDefaults(file, className);
      if (suffix === "recompute" && method === "POST")
        return handleGetArginfo(file, className);
    }
    throw new MockApiError(404, "Not Found");
  }

  if (rest[0] === "schedule") {
    if (rest.length === 1) {
      if (method === "GET") return { ...state.schedule };
      if (method === "POST") return handleSubmitExperiment(url, body);
      throw new MockApiError(405, "Method Not Allowed");
    }
    if (rest.length === 2 && method === "GET") {
      const rid = Number(rest[1]);
      if (!(rid in state.schedule))
        throw new MockApiError(404, `RID ${rid} not found in schedule`);
      return state.schedule[rid];
    }
    throw new MockApiError(404, "Not Found");
  }

  if (rest[0] === "scan") {
    // client.js posts to "api/scan/submit-and-wait" when wait_for_completion is
    // true, but the real backend only ever exposes POST /api/scan with a
    // wait_for_completion query param — there is no such route in api.py. We
    // support both paths defensively so the demo works regardless of that
    // pre-existing client.js/api.py mismatch (not something this package owns).
    if (rest.length === 1 && method === "POST")
      return handleSubmitScan(url, body);
    if (
      rest.length === 2 &&
      rest[1] === "submit-and-wait" &&
      method === "POST"
    ) {
      const forced = new URL(url);
      forced.searchParams.set("wait_for_completion", "true");
      return handleSubmitScan(forced, body);
    }
    throw new MockApiError(404, "Not Found");
  }

  if (rest[0] === "cancel" && rest.length === 1) {
    if (method === "POST") return handleCancel(url);
    throw new MockApiError(405, "Method Not Allowed");
  }

  if (rest[0] === "datasets") {
    if (rest.length === 1 && method === "GET") return { ...state.datasets };
    if (rest.length === 2 && rest[1] === "names" && method === "GET") {
      return { names: Object.keys(state.datasets) };
    }
    if (rest.length === 2 && rest[1] === "values" && method === "GET") {
      const names = (url.searchParams.get("names") ?? "")
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean);
      const out = {};
      for (const n of names)
        if (n in state.datasets) out[n] = state.datasets[n];
      return out;
    }
    throw new MockApiError(404, "Not Found");
  }

  if (rest[0] === "logs" && rest.length === 1) {
    if (method === "GET") return handleGetLogs(url);
    throw new MockApiError(405, "Method Not Allowed");
  }

  if (rest[0] === "health" && rest.length === 1) {
    if (method === "GET") return state.health;
    throw new MockApiError(405, "Method Not Allowed");
  }

  throw new MockApiError(404, "Not Found");
}

// ── fetch patch ──────────────────────────────────────────────────────────────

async function extractBody(input, init) {
  if (init && init.body != null) {
    if (typeof init.body === "string") {
      try {
        return JSON.parse(init.body);
      } catch {
        return null;
      }
    }
    return init.body;
  }
  if (
    typeof Request !== "undefined" &&
    input instanceof Request &&
    input.body
  ) {
    try {
      return await input.clone().json();
    } catch {
      return null;
    }
  }
  return null;
}

function isMockApiUrl(urlObj) {
  return (
    urlObj.origin === window.location.origin &&
    urlObj.pathname.startsWith("/api/")
  );
}

function patchFetch() {
  realFetchRef = window.fetch.bind(window);
  const realFetch = realFetchRef;

  window.fetch = async function mockFetch(input, init) {
    let urlObj;
    try {
      const raw = input instanceof Request ? input.url : input;
      urlObj = new URL(raw, window.location.href);
    } catch {
      return realFetch(input, init);
    }

    if (!isMockApiUrl(urlObj)) return realFetch(input, init);

    const method = (
      init?.method ||
      (input instanceof Request ? input.method : "GET") ||
      "GET"
    ).toUpperCase();
    const body = await extractBody(input, init);

    try {
      const result = await routeApi(method, urlObj, body);
      return jsonResponse(result);
    } catch (err) {
      if (err instanceof MockApiError)
        return jsonResponse({ detail: err.detail }, err.status);
      console.error(
        "[mockAdapter] unexpected error handling",
        method,
        urlObj.pathname,
        err,
      );
      return jsonResponse({ detail: String(err?.message ?? err) }, 500);
    }
  };
}

// ── EventSource shim ─────────────────────────────────────────────────────────

function extractStreamPrefix(urlStr) {
  try {
    const u = new URL(urlStr, window.location.href);
    const marker = "/api/datasets/stream/";
    const idx = u.pathname.indexOf(marker);
    if (idx === -1) return null;
    return decodeURIComponent(u.pathname.slice(idx + marker.length));
  } catch {
    return null;
  }
}

function isMockStreamUrl(urlStr) {
  try {
    const u = new URL(urlStr, window.location.href);
    return (
      u.origin === window.location.origin &&
      u.pathname.startsWith("/api/datasets/stream/")
    );
  } catch {
    return false;
  }
}

const HEARTBEAT_MS = 15000;

class MockEventSource extends EventTarget {
  constructor(url) {
    super();
    this.url = String(url);
    this.readyState = 0; // CONNECTING
    this.onopen = null;
    this.onmessage = null;
    this.onerror = null;
    this._prefix = extractStreamPrefix(this.url) || "";
    this._lastEventAt = Date.now();
    openEventSources.add(this);
    queueMicrotask(() => this._connect());
  }

  async _connect() {
    await ensureLoaded();
    if (this.readyState === 2) return; // already closed
    this.readyState = 1; // OPEN
    const openEvt = new Event("open");
    this.dispatchEvent(openEvt);
    if (typeof this.onopen === "function") this.onopen(openEvt);
    this._emit("init", getDatasetsForPrefix(this._prefix));
  }

  _emit(eventName, data) {
    if (this.readyState === 2) return;
    this._lastEventAt = Date.now();
    const evt = new MessageEvent(eventName, { data: JSON.stringify(data) });
    this.dispatchEvent(evt);
    const handler = this[`on${eventName}`];
    if (typeof handler === "function") handler(evt);
  }

  close() {
    this.readyState = 2;
    openEventSources.delete(this);
  }
}
MockEventSource.CONNECTING = 0;
MockEventSource.OPEN = 1;
MockEventSource.CLOSED = 2;

function patchEventSource() {
  const RealEventSource = window.EventSource;
  class EventSourceShim {
    constructor(url, opts) {
      if (isMockStreamUrl(url)) return new MockEventSource(url);
      // eslint-disable-next-line new-cap
      return new RealEventSource(url, opts);
    }
  }
  if (RealEventSource) {
    EventSourceShim.CONNECTING = RealEventSource.CONNECTING;
    EventSourceShim.OPEN = RealEventSource.OPEN;
    EventSourceShim.CLOSED = RealEventSource.CLOSED;
  }
  window.EventSource = EventSourceShim;
}

function flushSSE() {
  if (!pendingChanges.size && !pendingDeletes.size) return;
  for (const es of openEventSources) {
    if (es.readyState !== 1) continue;
    for (const key of pendingChanges) {
      if (key === es._prefix || key.startsWith(`${es._prefix}.`)) {
        es._emit("update", { [key]: state.datasets[key] });
      }
    }
    for (const key of pendingDeletes) {
      if (key === es._prefix || key.startsWith(`${es._prefix}.`)) {
        es._emit("delete", { key });
      }
    }
  }
  pendingChanges.clear();
  pendingDeletes.clear();
}

function flushHeartbeats() {
  const now = Date.now();
  for (const es of openEventSources) {
    if (es.readyState === 1 && now - es._lastEventAt >= HEARTBEAT_MS) {
      es._emit("heartbeat", {});
    }
  }
}

// ── Seeded RabiFlop live-scan animation (ports of mock_backend.py's
//    _step_live_rabi_scan) ───────────────────────────────────────────────────
// RID 4823's schedule item declares a 101-point rabi.pulse_duration scan (see
// the seeded schedule.json fixture); this animates the matching dataset
// (fragment_fqn, axis and channel names all agree — see the module docstring)
// so the live pane's identity is coherent, not a mismatched leftover demo.

const RABI_SCAN_PREFIX = "ndscan.rid_4823";
const RABI_SCAN_CHANNEL_KEYS = ["excitation", "dark_counts", "atom_number"];
const RABI_SCAN_RANGE = { start: 1e-6, stop: 5e-5, numPoints: 101 };
const RABI_SCAN_X_POINTS = linspace(
  RABI_SCAN_RANGE.start,
  RABI_SCAN_RANGE.stop,
  RABI_SCAN_RANGE.numPoints,
);
// Matches the schedule item's declared num_repeats: 2 (see schedule.json), so
// the streamed point count agrees with the "N/202" progress the frontend
// derives from it, and so the randomized-order-with-repeats behaviour
// exercises Plot1D's per-x mean/SEM error-bar rendering.
const RABI_SCAN_REPEATS = 2;
const RABI_PERIOD_S = 12e-6; // ~12 us Rabi period, a few oscillations across the 1-50 us scan range

let rabiScanPlan = [];
let rabiScanIdx = 0;
let rabiScanPhaseShift = 0.0;

function rabiSample(t, phaseShift) {
  let excitation =
    0.5 - 0.5 * Math.cos((2 * Math.PI * (t - phaseShift)) / RABI_PERIOD_S);
  excitation = Math.max(0, Math.min(1, excitation + gauss(0, 0.04)));
  return {
    excitation,
    dark_counts: 0.5 + gauss(0, 0.03),
    atom_number: 50000.0 + 30000.0 * excitation + gauss(0, 3000.0),
  };
}

function shuffledRabiScanPlan() {
  const plan = [];
  for (const x of RABI_SCAN_X_POINTS)
    for (let i = 0; i < RABI_SCAN_REPEATS; i++) plan.push(x);
  return shuffle(plan);
}

function tickRabiScanCheat() {
  // Defensive: only animate once the seeded fixture datasets are present.
  if (!(`${RABI_SCAN_PREFIX}.axes` in state.datasets)) return;
  if (rabiScanPlan.length === 0) rabiScanPlan = shuffledRabiScanPlan();
  if (rabiScanIdx >= rabiScanPlan.length) {
    rabiScanPlan = shuffledRabiScanPlan();
    rabiScanIdx = 0;
    rabiScanPhaseShift = Math.max(
      RABI_SCAN_RANGE.start,
      Math.min(
        RABI_SCAN_RANGE.stop,
        rabiScanPhaseShift + (Math.random() * 2 - 1) * 5e-6,
      ),
    );
    setDataset(`${RABI_SCAN_PREFIX}.points.axis_0`, []);
    for (const k of RABI_SCAN_CHANNEL_KEYS)
      setDataset(`${RABI_SCAN_PREFIX}.points.channel_${k}`, []);
  }
  const x = rabiScanPlan[rabiScanIdx++];
  const sample = rabiSample(x, rabiScanPhaseShift);
  const axis = [
    ...(state.datasets[`${RABI_SCAN_PREFIX}.points.axis_0`]?.[1] ?? []),
    x,
  ];
  setDataset(`${RABI_SCAN_PREFIX}.points.axis_0`, axis);
  for (const k of RABI_SCAN_CHANNEL_KEYS) {
    const arr = [
      ...(state.datasets[`${RABI_SCAN_PREFIX}.points.channel_${k}`]?.[1] ?? []),
      sample[k],
    ];
    setDataset(`${RABI_SCAN_PREFIX}.points.channel_${k}`, arr);
  }
}

function tickRepeat0D() {
  const t = Date.now() / 1000;
  setDataset(
    "ndscan.rid_1.point.ch0",
    0.5 + 0.3 * Math.sin(t * 0.5) + gauss(0, 0.05),
  );
  setDataset(
    "ndscan.rid_1.point.ch1",
    0.3 + 0.2 * Math.sin(t * 0.7 + 1.0) + gauss(0, 0.04),
  );
  setDataset(
    "ndscan.rid_1.point.ch2",
    0.7 + 0.15 * Math.sin(t * 0.3 + 2.0) + gauss(0, 0.03),
  );
  setDataset(
    "ndscan.rid_1.point.ch3",
    0.1 + 0.4 * Math.sin(t * 0.4 + 3.0) + gauss(0, 0.06),
  );
}

const IMAGE_SPECS = [
  { key: "camera_image", size: 64, kind: "blob" },
  { key: "mot_fluorescence_image", size: 64, kind: "blob" },
  { key: "ion_chain_image", size: 96, kind: "chain" },
  { key: "background_image", size: 48, kind: "noise" },
  { key: "absorption_image", size: 80, kind: "rings" },
];

function toArtiqOrder(rows) {
  const h = rows.length;
  const w = rows[0].length;
  const out = [];
  for (let col = 0; col < w; col++) {
    const c = [];
    for (let row = 0; row < h; row++) c.push(rows[row][col]);
    out.push(c);
  }
  return out;
}

function generateImage(size, kind, seed) {
  const t = Date.now() / 1000 + seed;
  const rows = [];
  if (kind === "chain") {
    const nIons = 5;
    const cy = size / 2 + 3 * Math.sin(t * 0.4);
    const sigma = 4.0;
    const centres = Array.from(
      { length: nIons },
      (_, i) => (size * (i + 1)) / (nIons + 1),
    );
    for (let row = 0; row < size; row++) {
      const r = [];
      for (let col = 0; col < size; col++) {
        let v = 0.0;
        for (const cx of centres)
          v +=
            200 *
            Math.exp(-((row - cy) ** 2 + (col - cx) ** 2) / (2 * sigma ** 2));
        v += gauss(0, 3);
        r.push(clampByte(v));
      }
      rows.push(r);
    }
    return toArtiqOrder(rows);
  }
  if (kind === "rings") {
    const cx = size / 2;
    const cy = size / 2;
    for (let row = 0; row < size; row++) {
      const r = [];
      for (let col = 0; col < size; col++) {
        const rad = Math.hypot(row - cy, col - cx);
        let v = 128 + 100 * Math.cos(rad * 0.8 - t * 1.5);
        v += gauss(0, 5);
        r.push(clampByte(v));
      }
      rows.push(r);
    }
    return toArtiqOrder(rows);
  }
  if (kind === "noise") {
    const base = 30 + 10 * Math.sin(t * 0.2);
    for (let row = 0; row < size; row++) {
      const r = [];
      for (let col = 0; col < size; col++)
        r.push(clampByte(base + gauss(0, 8)));
      rows.push(r);
    }
    return toArtiqOrder(rows);
  }
  // blob (default)
  const cx = size / 2 + size * 0.3 * Math.sin(t * 0.3);
  const cy = size / 2 + size * 0.3 * Math.cos(t * 0.2);
  const sigma = size / 8 + (size / 16) * Math.sin(t * 0.15);
  for (let row = 0; row < size; row++) {
    const r = [];
    for (let col = 0; col < size; col++) {
      let v =
        220 * Math.exp(-((row - cy) ** 2 + (col - cx) ** 2) / (2 * sigma ** 2));
      v += gauss(0, 4);
      r.push(clampByte(v));
    }
    rows.push(r);
  }
  return toArtiqOrder(rows);
}

function tickImages() {
  for (let i = 0; i < IMAGE_SPECS.length; i++) {
    const spec = IMAGE_SPECS[i];
    setDataset(spec.key, generateImage(spec.size, spec.kind, i * 1.7));
  }
}

// ── Global tick loop ─────────────────────────────────────────────────────────

const TICK_MS = 500;
let tickTimer = null;

function tick() {
  if (!state.explist) return; // fixtures not loaded yet
  tickRepeat0D();
  tickImages();
  tickRabiScanCheat();
  for (const run of activeRuns.values()) tickNdscanRun(run);
  flushHeartbeats();
  flushSSE();
}

function startTicking() {
  if (tickTimer) return;
  tickTimer = setInterval(tick, TICK_MS);
}

function stopTicking() {
  if (tickTimer) {
    clearInterval(tickTimer);
    tickTimer = null;
  }
}

// ── Demo banner ──────────────────────────────────────────────────────────────

const BANNER_DISMISS_KEY = "artiq_http.mock.bannerDismissed";

function mountDemoBanner() {
  if (typeof document === "undefined") return;
  if (sessionStorage.getItem(BANNER_DISMISS_KEY) === "1") return;

  const style = document.createElement("style");
  style.textContent = `
    #artiq-mock-banner {
      position: fixed;
      top: 10px;
      right: 10px;
      z-index: 2147483000;
      display: flex;
      align-items: center;
      gap: 8px;
      background: var(--b-surface-raised, #1b1f23);
      color: var(--b-fg, #e8e6df);
      border: 1px solid var(--b-border-strong, #3d444c);
      border-radius: var(--b-r-pill, 999px);
      padding: 6px 8px 6px 12px;
      font: 500 12px/1.2 var(--b-font-ui, system-ui, sans-serif);
      box-shadow: 0 2px 10px rgba(0, 0, 0, 0.35);
    }
    #artiq-mock-banner .artiq-mock-banner__dot {
      width: 6px;
      height: 6px;
      border-radius: 50%;
      background: var(--b-accent, #f08a4d);
      flex: none;
    }
    #artiq-mock-banner button {
      appearance: none;
      border: none;
      background: transparent;
      color: inherit;
      font-size: 14px;
      line-height: 1;
      cursor: pointer;
      padding: 2px 6px;
      margin-left: 2px;
      border-radius: var(--b-r-ctl, 4px);
    }
    #artiq-mock-banner button:hover {
      background: var(--b-accent-wash, rgba(240, 138, 77, 0.14));
    }
    @media (prefers-reduced-motion: no-preference) {
      #artiq-mock-banner {
        animation: artiq-mock-banner-in 160ms ease-out;
      }
    }
    @keyframes artiq-mock-banner-in {
      from {
        opacity: 0;
        transform: translateY(-4px);
      }
      to {
        opacity: 1;
        transform: none;
      }
    }
  `;
  document.head.appendChild(style);

  const el = document.createElement("div");
  el.id = "artiq-mock-banner";
  el.setAttribute("role", "status");

  const dot = document.createElement("span");
  dot.className = "artiq-mock-banner__dot";
  dot.setAttribute("aria-hidden", "true");

  const label = document.createElement("span");
  label.textContent = "demo — mock data, no ARTIQ master";

  const dismiss = document.createElement("button");
  dismiss.type = "button";
  dismiss.setAttribute("aria-label", "Dismiss demo banner");
  dismiss.textContent = "×";
  dismiss.addEventListener("click", () => {
    sessionStorage.setItem(BANNER_DISMISS_KEY, "1");
    el.remove();
  });

  el.append(dot, label, dismiss);

  const mount = () => document.body.appendChild(el);
  if (document.body) mount();
  else document.addEventListener("DOMContentLoaded", mount, { once: true });
}

// ── Install ──────────────────────────────────────────────────────────────────

function installMockAdapter() {
  if (window.__artiqHttpMockInstalled) return;
  window.__artiqHttpMockInstalled = true;

  patchFetch();
  patchEventSource();
  mountDemoBanner();

  if (typeof document !== "undefined") {
    if (!document.hidden) startTicking();
    document.addEventListener("visibilitychange", () => {
      if (document.hidden) stopTicking();
      else startTicking();
    });
  } else {
    startTicking();
  }

  // Warm the fixture load immediately rather than waiting for the first API
  // call, so the app's first render doesn't pay the extra round trip.
  ensureLoaded().catch((err) =>
    console.error("[mockAdapter] failed to load fixtures", err),
  );
}

if (import.meta.env.VITE_MOCK === "1") {
  installMockAdapter();
}
