# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .exp_id import ExpId
    from .experiment_defaults import ExperimentDefaults
    from .experiment_entry import ExperimentEntry
    from .experiment_list import ExperimentList
    from .http_validation_error import HttpValidationError
    from .schedule_item import ScheduleItem
    from .submit_and_wait_result import SubmitAndWaitResult
    from .validation_error import ValidationError
    from .validation_error_loc_item import ValidationErrorLocItem
_dynamic_imports: typing.Dict[str, str] = {
    "ExpId": ".exp_id",
    "ExperimentDefaults": ".experiment_defaults",
    "ExperimentEntry": ".experiment_entry",
    "ExperimentList": ".experiment_list",
    "HttpValidationError": ".http_validation_error",
    "ScheduleItem": ".schedule_item",
    "SubmitAndWaitResult": ".submit_and_wait_result",
    "ValidationError": ".validation_error",
    "ValidationErrorLocItem": ".validation_error_loc_item",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ExpId",
    "ExperimentDefaults",
    "ExperimentEntry",
    "ExperimentList",
    "HttpValidationError",
    "ScheduleItem",
    "SubmitAndWaitResult",
    "ValidationError",
    "ValidationErrorLocItem",
]
