# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        ExpId,
        ExperimentDefaults,
        ExperimentEntry,
        ExperimentList,
        HttpValidationError,
        ScheduleItem,
        SubmitAndWaitResult,
        ValidationError,
        ValidationErrorLocItem,
    )
    from .errors import UnprocessableEntityError
    from ._default_clients import DefaultAioHttpClient, DefaultAsyncHttpxClient
    from .client import ArtiqClient, AsyncArtiqClient
_dynamic_imports: typing.Dict[str, str] = {
    "ArtiqClient": ".client",
    "AsyncArtiqClient": ".client",
    "DefaultAioHttpClient": "._default_clients",
    "DefaultAsyncHttpxClient": "._default_clients",
    "ExpId": ".types",
    "ExperimentDefaults": ".types",
    "ExperimentEntry": ".types",
    "ExperimentList": ".types",
    "HttpValidationError": ".types",
    "ScheduleItem": ".types",
    "SubmitAndWaitResult": ".types",
    "UnprocessableEntityError": ".errors",
    "ValidationError": ".types",
    "ValidationErrorLocItem": ".types",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ArtiqClient",
    "AsyncArtiqClient",
    "DefaultAioHttpClient",
    "DefaultAsyncHttpxClient",
    "ExpId",
    "ExperimentDefaults",
    "ExperimentEntry",
    "ExperimentList",
    "HttpValidationError",
    "ScheduleItem",
    "SubmitAndWaitResult",
    "UnprocessableEntityError",
    "ValidationError",
    "ValidationErrorLocItem",
]
