#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SDK_SRC_DIR="${ROOT_DIR}/sdks/python"
SDK_WHEEL_DIR="${ROOT_DIR}/resources/artiq-sdk"
SKILL_RESOURCES_DIR="${ROOT_DIR}/skills/artiq-http-sdk/resources"
FERN_DOCS_DIR="${ROOT_DIR}/fern"
SDK_DOCS_DIR="${SKILL_RESOURCES_DIR}/artiq-http-docs"

mkdir -p "${SKILL_RESOURCES_DIR}"

rm -rf "${SKILL_RESOURCES_DIR}/artiq-http-sdk"
rm -rf "${SDK_DOCS_DIR}"

# Confirm that wheel artifacts have been built.
if ! ls "${SDK_WHEEL_DIR}"/artiq_http_client-*.whl >/dev/null 2>&1; then
  echo "Error: SDK wheel not found in ${SDK_WHEEL_DIR}. Run npm run build:fern_sdk_wheel first." >&2
  exit 1
fi

if [ ! -f "${SDK_WHEEL_DIR}/LATEST_SDK.txt" ]; then
  echo "Error: LATEST_SDK.txt not found in ${SDK_WHEEL_DIR}." >&2
  exit 1
fi

# Bundle markdown docs for skill consumers.
mkdir -p "${SDK_DOCS_DIR}"

if [ -f "${FERN_DOCS_DIR}/docs.yml" ]; then
  cp "${FERN_DOCS_DIR}/docs.yml" "${SDK_DOCS_DIR}/docs.yml"
fi

if [ -f "${FERN_DOCS_DIR}/docs/pages/overview.mdx" ]; then
  awk '
    BEGIN { frontmatter = 0 }
    NR == 1 && $0 == "---" { frontmatter = 1; next }
    frontmatter == 1 && $0 == "---" { frontmatter = 0; next }
    frontmatter == 1 { next }
    { print }
  ' "${FERN_DOCS_DIR}/docs/pages/overview.mdx" > "${SDK_DOCS_DIR}/overview.md"
fi

if [ -f "${SDK_SRC_DIR}/reference.md" ]; then
  cp "${SDK_SRC_DIR}/reference.md" "${SDK_DOCS_DIR}/api-reference.md"
fi

LLMS_INDEX_SRC=""
for candidate in \
  "${FERN_DOCS_DIR}/llms.txt" \
  "${FERN_DOCS_DIR}/docs/llms.txt"; do
  if [ -f "${candidate}" ]; then
    LLMS_INDEX_SRC="${candidate}"
    break
  fi
done

LLMS_FULL_SRC=""
for candidate in \
  "${FERN_DOCS_DIR}/llms-full.txt" \
  "${FERN_DOCS_DIR}/llms_full.txt" \
  "${FERN_DOCS_DIR}/docs/llms-full.txt" \
  "${FERN_DOCS_DIR}/docs/llms_full.txt"; do
  if [ -f "${candidate}" ]; then
    LLMS_FULL_SRC="${candidate}"
    break
  fi
done

if [ -z "${LLMS_INDEX_SRC}" ] || [ -z "${LLMS_FULL_SRC}" ]; then
  echo "Error: Fern-generated LLM docs were not found." >&2
  echo "Expected llms files in fern/ or fern/docs/." >&2
  echo "Generate them in your Fern docs pipeline before running this sync." >&2
  exit 1
fi

cp "${LLMS_INDEX_SRC}" "${SDK_DOCS_DIR}/llms.txt"
cp "${LLMS_FULL_SRC}" "${SDK_DOCS_DIR}/llms-full.txt"
cp "${LLMS_FULL_SRC}" "${SDK_DOCS_DIR}/llms_full.txt"

cat > "${SDK_DOCS_DIR}/README.md" <<'EOF'
# ARTIQ HTTP SDK Docs

This directory contains markdown-form docs bundled with the skill:

- `overview.md`: high-level usage overview copied from Fern docs content.
- `api-reference.md`: endpoint and method reference generated by Fern SDK generation.
- `docs.yml`: Fern docs navigation and API reference wiring.
- `llms.txt`: Fern-generated LLM index.
- `llms_full.txt`: Fern-generated full LLM context.
- `llms-full.txt`: alias of Fern full LLM context.

When using the skill, read these files first before issuing direct HTTP calls.
EOF
