services:
  artiq-master:
    build: .
    container_name: artiq-test-master
    ports:
      - "3250:3250"
      - "3251:3251"
      - "1066:1066"
      - "1067:1067"
    volumes:
      - ./repository:/artiq/repository
      - ./device_db.py:/artiq/device_db.py
    restart: "no"
